export const AssetSet = [
    {  
        id: 1,  
        name: "Tesla",  
        ticker: "TSLA-T",  
        price: 245.67,  
        change: 5.23,  
        volume: "$2.3B",  
        category: "stocks",  
        logo: "🚗",  
    },  
    {  
        id: 2,  
        name: "Apple",  
        ticker: "AAPL-T",  
        price: 189.45,  
        change: 3.45,  
        volume: "$1.8B",  
        category: "stocks",  
        logo: "🍎",  
    },  
    {  
        id: 3,  
        name: "Microsoft",  
        ticker: "MSFT-T",  
        price: 378.92,  
        change: -1.23,  
        volume: "$1.2B",  
        category: "stocks",  
        logo: "💻",  
    },  
    {  
        id: 4,  
        name: "Amazon",  
        ticker: "AMZN-T",  
        price: 145.32,  
        change: 2.87,  
        volume: "$2.1B",  
        category: "stocks",  
        logo: "📦",  
    },  
    {  
        id: 5,  
        name: "Google",  
        ticker: "GOOGL-T",  
        price: 138.21,  
        change: 1.95,  
        volume: "$1.5B",  
        category: "stocks",  
        logo: "🔍",  
    },  
    {  
        id: 6,  
        name: "NVIDIA",  
        ticker: "NVDA-T",  
        price: 485.09,  
        change: 8.45,  
        volume: "$3.8B",  
        category: "stocks",  
        logo: "🎮",  
    },  
    {  
        id: 7,  
        name: "Meta",  
        ticker: "META-T",  
        price: 312.45,  
        change: -2.15,  
        volume: "$1.9B",  
        category: "stocks",  
        logo: "📘",  
    },  
    {  
        id: 8,  
        name: "Netflix",  
        ticker: "NFLX-T",  
        price: 425.67,  
        change: 4.32,  
        volume: "$890M",  
        category: "stocks",  
        logo: "🎬",  
    },  
    // Commodities  
    {  
        id: 9,  
        name: "Gold",  
        ticker: "AU-T",  
        price: 2045.23,  
        change: 2.15,  
        volume: "$890M",  
        category: "commodities",  
        logo: "✨",  
    },  
    {  
        id: 10,  
        name: "Silver",  
        ticker: "AG-T",  
        price: 24.56,  
        change: 1.87,  
        volume: "$450M",  
        category: "commodities",  
        logo: "🥈",  
    },  
    {  
        id: 11,  
        name: "Oil (WTI)",  
        ticker: "WTI-T",  
        price: 78.45,  
        change: -2.34,  
        volume: "$650M",  
        category: "commodities",  
        logo: "🛢️",  
    },  
    {  
        id: 12,  
        name: "Natural Gas",  
        ticker: "NG-T",  
        price: 2.87,  
        change: -3.21,  
        volume: "$320M",  
        category: "commodities",  
        logo: "🔥",  
    },  
    {  
        id: 13,  
        name: "Platinum",  
        ticker: "PLAT-T",  
        price: 945.32,  
        change: 0.95,  
        volume: "$180M",  
        category: "commodities",  
        logo: "⚪",  
    },  
    {  
        id: 14,  
        name: "Copper",  
        ticker: "COP-T",  
        price: 3.78,  
        change: 1.45,  
        volume: "$290M",  
        category: "commodities",  
        logo: "🔧",  
    },  
    // Crypto  
    {  
        id: 15,  
        name: "Bitcoin",  
        ticker: "BTC-T",  
        price: 42305.67,  
        change: 8.92,  
        volume: "$3.2B",  
        category: "crypto",  
        logo: "₿",  
    },  
    {  
        id: 16,  
        name: "Ethereum",  
        ticker: "ETH-T",  
        price: 2204.56,  
        change: 6.78,  
        volume: "$1.9B",  
        category: "crypto",  
        logo: "Ξ",  
    },  
    {  
        id: 17,  
        name: "Binance Coin",  
        ticker: "BNB-T",  
        price: 245.78,  
        change: 4.56,  
        volume: "$780M",  
        category: "crypto",  
        logo: "🔶",  
    },  
    {  
        id: 18,  
        name: "Cardano",  
        ticker: "ADA-T",  
        price: 0.58,  
        change: -1.23,  
        volume: "$320M",  
        category: "crypto",  
        logo: "💙",  
    },  
    {  
        id: 19,  
        name: "Solana",  
        ticker: "SOL-T",  
        price: 98.45,  
        change: 12.34,  
        volume: "$1.1B",  
        category: "crypto",  
        logo: "🟣",  
    },  
    {  
        id: 20,  
        name: "Polkadot",  
        ticker: "DOT-T",  
        price: 7.89,  
        change: 3.21,  
        volume: "$290M",  
        category: "crypto",  
        logo: "⚫",  
    },  
    {  
        id: 21,  
        name: "Ripple",  
        ticker: "XRP-T",  
        price: 0.62,  
        change: -0.87,  
        volume: "$1.4B",  
        category: "crypto",  
        logo: "🌊",  
    },  
    {  
        id: 22,  
        name: "Dogecoin",  
        ticker: "DOGE-T",  
        price: 0.089,  
        change: 15.67,  
        volume: "$450M",  
        category: "crypto",  
        logo: "🐕",  
    },  
    // Currencies  
    {  
        id: 23,  
        name: "EUR/USD",  
        ticker: "EURUSD-T",  
        price: 1.0845,  
        change: 0.45,  
        volume: "$1.1B",  
        category: "currencies",  
        logo: "💱",  
    },  
    {  
        id: 24,  
        name: "GBP/USD",  
        ticker: "GBPUSD-T",  
        price: 1.2734,  
        change: -0.23,  
        volume: "$890M",  
        category: "currencies",  
        logo: "🇬🇧",  
    },  
    {  
        id: 25,  
        name: "USD/JPY",  
        ticker: "USDJPY-T",  
        price: 149.87,  
        change: 0.78,  
        volume: "$750M",  
        category: "currencies",  
        logo: "🇯🇵",  
    },  
    {  
        id: 26,  
        name: "USD/CHF",  
        ticker: "USDCHF-T",  
        price: 0.8956,  
        change: -0.12,  
        volume: "$420M",  
        category: "currencies",  
        logo: "🇨🇭",  
    },  
    {  
        id: 27,  
        name: "AUD/USD",  
        ticker: "AUDUSD-T",  
        price: 0.6543,  
        change: 1.23,  
        volume: "$380M",  
        category: "currencies",  
        logo: "🇦🇺",  
    },  
    {  
        id: 28,  
        name: "USD/CAD",  
        ticker: "USDCAD-T",  
        price: 1.3654,  
        change: -0.56,  
        volume: "$410M",  
        category: "currencies",  
        logo: "🇨🇦",  
    },  
]